"""initial

Revision ID: 13f401d203e2
Revises: 
Create Date: 2026-02-26 13:02:11.714536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f401d203e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('admin','regular')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('password_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('account_username', sa.String(length=120), nullable=False),
    sa.Column('password_value', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_entries_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_entries_updated_by_user_id'), ['updated_by_user_id'], unique=False)

    op.create_table('password_entry_categories',
    sa.Column('password_entry_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['password_entry_id'], ['password_entries.id'], ),
    sa.PrimaryKeyConstraint('password_entry_id', 'category_id')
    )
    with op.batch_alter_table('password_entry_categories', schema=None) as batch_op:
        batch_op.create_index('ix_pwcat_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_pwcat_password_entry_id', ['password_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_entry_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_pwcat_password_entry_id')
        batch_op.drop_index('ix_pwcat_category_id')

    op.drop_table('password_entry_categories')
    with op.batch_alter_table('password_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_entries_updated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_entries_created_by_user_id'))

    op.drop_table('password_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
